var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                     yyy                           o            ",
   "                               yyyyyyyyyy          o              xxx        yyy",
   "                          yyyyyyyyyyyyyyyyyyy      xx            xx!xx    yyyyyy",
   "                             yyyyyyyyyyy     xx            xx    x!!!x   yyyyyy ",
   "                                    ooo                          xx!xx     yyyy ",
   "             yyyy                  xxxxx         x!!!!!!x         xvx           ",
   "  x      yyyyyyyyyy                     yyy      xxxxxxxx                    x  ",
   "  x    yyyyyyyyy                      yyyyyyy                                x  ",
   "  x      yyy        xxx                    o                                 x  ",
   "  x           oo               xxx       xxxxx     yyy  xxx                o x  ",
   "  x          xxxx                          m     yyyyyyy          xx       xxx  ",
   "  x  @       x  x                                         !!!!!!!x  xx!!!!!!!x  ",
   "  xxxxx!!!xxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx    !xxxxxxx   xxxxxxxxx  ",
   "      xxxxx                   x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x!!x                        xxxxxxx                                    x!x  ",
   "                                      x!!x                     xxxx     xxxx       yyyyyyyyyyy       o       x!x  ",
   "                                      x!!xxxxxxxxxx           xx           xx        yyyyyyy        ooo     xx!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                     ooooo     x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    ooooooo    x!x  ",
   "                                                xx!x         x       o                yy         ooooooooo  xx!x  ",
   "                                                 x!x         x                       yyyyy    xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     xxxxx               yyy      !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |       |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                         yyyyyyyy              x     x            xxxxxxx        xxx         xxx                  ",
   "                    yyyyyyyyyyyyyyy            x     x                 yyyy      x x         x x                  ",
   "          yyyyyyyyyyyyyyyyyyyyyyyyyyyyy        x     x          yyyyyyyyyyyyyy     x         x                    ",
   "       yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy          xo    x               yyyyyyyyyyyyyyxx        x                    ",
   "              yyyyyyyyyyyyyyyyyyyy             xx    x                 o      yyyy x         x                    ",
   "                                               x     x               x   x         x        xx                    ",
   "               xxxxxxx        xxx   xxx        x     x       oo      x   x         x         x                    ",
   "              xx     xx         x o x          x    ox     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x   x      yyyyx    xx               x   x   x              xx                    ",
   "     @       x         x        x   x    yyyyyyx     x               x   x   x               x                    ",
   "    xxx   o  x         x        x   x       yyyx     x               x   xxxxx   xxxxxx      x                    ",
   "    x x  xxx x         x       xx o xx         x     x               x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x           x x        xx                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx   m   xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x                      xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x          ooo ooo    xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                         yyy                                                                                  ",
   "                       yyyyyyyyy                                                                              ",
   "                      yyyyyyyyyyyyyyyyyyo                                                                     ",
   "                             yyyyyyyyyy o                                                                     ",
   "                                yyyy    x                                yyyy                                 ",
   "                                        x                            yyyyyyyyyyyyyy                           ",
   "                                        x                       yyyyyyyyyyyyyyyyyyyyyyyyyyy                   ",
   "                                        x                             yyyyyyyyyyyyyyy                         ",
   "                            yyyyyyyyyy xxx                                       yyyyyyyyyyyy yyyyy           ",
   "              yyyyy     yyyyyyyyyyyyyyyx x                 !!!        !!!  xxx      yyyyyyyyyyy               ",
   "            yyyyyyyyyyyyyyyyyyyyyyyyyy x x                 !x!        !x!                  yyy                ",
   "                 yyyyyyyyyyy          xx xx                 x    m     x                                      ",
   "                            o         x   x                 x          x       xxx                            ",
   "                            o         x   x                 x  o o o o x      x!!!x                           ",
   "                            xx        x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x  oo  x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x         yyy                  ",
   "                                      x   x           x                     xxx           yyyyyyy             ",
   "                              xxx     x   x           x                                     yyyyyy            ",
   "       yyyyy                          x   x= = = =    x            xxx                         yy             ",
   "    yyyyyyyyyyyy                      x   x           x           x!!!x       o                               ",
   "          yyyyyyyyyyyyyyyyyyyyyyy     x   x    = = = =x            xxx       xxx                              ",
   "              yyyyyyyyyyyyyyyyyyyyyy xx   xx          x                     x!!!x                             ",
   "                                      x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx  xx xxx          x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx     xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                o                       ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xx xx                             x  ",
   "  x                           x           x                              x o x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxxxxxx                             x  ",
   "  x                xxx                    x                              x         xxx           o         x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x        ox  ",
   "  x               oxxxo       x    xxx!!!!x                             x x        xxx          xxx      oox  ",
   "  x                xxx        xxxxxxxxxxxxx xxx         xxxxx          xx xx                    xxx     ooox  ",
   "  x      @    o     x         x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!xx   xx                    x     oooox  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],

  ["                                                                                                  xxx x       ",
   "                                                                                                o     x       ",
   "                                                                                               oo xxxxx       ",
   "                                                    yyy                                       ooo x           ",
   "                                                 yyyyyyyyyy                       xxxx       oooo x xxx       ",
   "                    m                        yyyyyyyyyyyyyyyyyyyyy    yyy                   ooooo x x x       ",
   "                                                   yyyyyyyyyyyy                            oooooo xxx x       ",
   "                   xxx                                                                    ooooooo     x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x  o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                               yy                 x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                yyyyyyy           xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                          yyyyyyyy                                                            ",
   "          o              xxx            yyyyyyyyyyyy      xx                                                  ",
   "                                            yyyyyy                                                            ",
   "                                               yy                                                             ",
   "         yyy                                          xx                                                      ",
   "      yyyyyyyy     xxx         xxx                                                                            ",
   "        yyyy                                                                                                  ",
   "                          o                   xxx                               x      x                      ",
   "                                                          xx     xx                                           ",
   "  yyyy       xxx         xxx         xxx                                 x                  x    yy           ",
   " yyy                                                                               o             yyyyyy   yy  ",
   "                                                                 ||                o               yyy        ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  xx    xx                        ",
   "  x  @      x  xx   o   xxxxx   o   xxxxx                                                           o o o     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                   xxx             ",
   "        x=                  =                =x   x                     xxx                     xxxxxxxxxxxx  ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],

  ["                                                                                                              ",
   "                                          yyyyyyyy                                                            ",
   "                                        yyyyyyyyyyyy                                                          ",
   "                                            yyyyyy                 x     x      xx      x      x              ",
   "                                               yy                   x   x    xx    xx   x      x              ",
   "         yyy                                                         x x    x        x  x      x              ",
   "      yyyyyyyy                                                        x      xx    xx    x    x               ",
   "        yyyy                                                          x         xx         xx                 ",
   "                                                                                                              ",
   "                               yyy                                 x         x   x   x    x   x               ",
   "  yyyy                       yyyyy                                 x    x    x   x   x x  x   x   yyyy        ",
   " yyy                       yyyyyyyyy                                x  x x  x    x   x  x x   x   yyyyyyyyyyy ",
   "    @ ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo  xx   xx     x   x   xx   m  o      yyy   ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
